spring:
  application:
    name: commerce-registry-service

server:
  port: 8761

eureka:
  instance:
    hostname: commerce-registry-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      preferIpAddress: true

